### ISSUE TITLE
libicu / icu-libs on FreeBSD not found, yet they are installed in a current version

### ISSUE THREAD

**Issue by recordscience** [slskd/slskd#905]
Trying to run slskd as a daemon on FreeBSD12.3-p6 and it tells me it can not find the icu-libs, albeit devel/icu is installed in the newest version and /usr/local/libdata/pkgconfig/icu-i18n.pc is present.
Can i link that or something else to the proper path to make it work?

**Comment by jpdillingham** [comment]
I've added `freebsd-x64` and `freebsd-arm64` runtime targets in #906.  Please give one of these a shot (once they are published in a little bit!) and see if that resolves your issue (I'm somewhat doubtful).

I did find [this documentation](https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/freebsd-requirements.md) that describes the dependencies needed to build the dotnet runtime; it may provide some clues but will almost certainly list stuff you don't need, since you aren't building the runtime, just running it.

There's also a somewhat lengthy open issue in the runtime repo [here](https://github.com/dotnet/runtime/issues/14537).  The fact that it's still open is not a great sign.

I'll leave this issue open; if you happen to get it working please follow up!

**Comment by jpdillingham** [comment]
Unfortunately the new `freebsd` runtime IDs are just for show and the release based on #906 failed.  I'm reverting the inclusion of those RIDs in #907.

I think there may be a way to get this working but you'll likely need to compile your own .NET runtime, and if you get that working, you'll need to build slskd from source and omit the self-contained executable flags.

**Comment by recordscience** [comment]
Sad it did not work out. Hopefully some times this can be implemented.
Alternatively, since i dont need all that unicode stuff since the files are in ANSI only, maybe there is a way i can set the parameter "configuration flag System.Globalization.Invariant to true", somehow for slskd on FreeBSD, too?

**Comment by jonasoh** [comment]
FWIW, I use slskd under FreeBSD/x64 with decent results. I experience the occasional crash but otherwise it's working very well. 

I use it with SDK 7.0 from https://github.com/sec/dotnet-core-freebsd-source-build. After building, I had to symlink `bin/Release/net7.0/libe_sqlite3.so` -> `/usr/local/lib/libsqlite3.so` (from `pkg install sqlite3`). I'm not a .NET guy but this had to do with not being able to install a package. Apparently the native shared lib is similar enough that it works.

**Comment by jpdillingham** [comment]
@jonasoh thanks for sharing the workaround! I've updated the title of the issue to reflect this.

**Comment by panzertime** [comment]
I've been using slskd in a FreeBSD 14.0 jail for a few months now, and it works pretty well. I'm running .NET 8.0.100 and had to do that same SQLite library symlink to get it to work. I don't know which of my issues (may) have been fixed in a newer build of `dotnet`.

Notes:

1. .NET doesn't want to be built in a jail, or run in a jail, and will give you some errors. I had to add `allow.mlock` to my jail's config to get this to work. [I think this is fixed or will be fixed soon](https://github.com/dotnet/runtime/issues/14537#issuecomment-2039400277).
2. Sometimes when I do a search, .NET crashes. It only happens when on some searches, but it seems like it always happens when I do certain searches. I have the service set up to restart when it fails so it's not the end of the world. Once it resumes, the failed search shows in the UI as still going, but the stop button does nothing and I can't delete it without going into the DB and changing the search status to completed first. Sometimes the stack trace is a little different, but it's always error `0x80131506` and it always passes through `ThreadPoolWorkQueue.Dispatch()`. 

Anyway, slskd on FreeBSD is pretty dang serviceable as-is. I suspect the issues are entirely within dotnet, but I felt inspired to share.


A stack trace from the error I mentioned:
> `Fatal error. Internal CLR error. (0x80131506)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task, System.Threading.Tasks.ConfigureAwaitOptions)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult()
   at Soulseek.Network.PeerConnectionManager+<>c__DisplayClass33_0+<<AddOrUpdateMessageConnectionAsync>g__GetConnection|2>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Soulseek.Network.PeerConnectionManager+<>c__DisplayClass33_0+<<AddOrUpdateMessageConnectionAsync>g__GetConnection|2>d, Soulseek, Version=6.4.1.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Soulseek.Network.PeerConnectionManager+<>c__DisplayClass33_0+<<AddOrUpdateMessageConnectionAsync>g__GetConnection|2>d, Soulseek, Version=6.4.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Soulseek.Network.PeerConnectionManager+<>c__DisplayClass33_0+<<AddOrUpdateMessageConnectionAsync>g__GetConnection|2>d, Soulseek, Version=6.4.1.0, Culture=neutral, PublicKeyToken=null]].ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()`

**Comment by 320x200** [comment]
Hi there,

I've never used dotnet before so it was not entirely sure how to build/install, took a bit of time, leaving my steps here for whoever in the same situation as me in the future. Thanks a lot for `slskd`, still missing a few things, but it's already my fav slsk client!

- `pkg install dotnet sqlite3`
- `git clone https://github.com/slskd/slskd`
- `cd slskd`
- in `src/web`
	- `npm install`
	- `npm run build`
- `rm -rf src/slskd/wwwroot/`
- `cp -av src/web/build src/slskd/wwwroot`
- in `src/slskd`
	-  `sed -i '' s/net8.0/net9.0/ slskd.csproj`
	- `dotnet build --no-incremental --nologo --configuration Release`
	- `dotnet publish --configuration Release --framework net9.0 --runtime freebsd.15-x64 -p:PublishSingleFile=true -p:ReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true -p:CopyOutputSymbolsToPublishDirectory=false --self-contained --output ../../dist/freebsd-x64`
- in `dist/freebsd-x64`
	- `ln -s /usr/local/lib/libsqlite3.so libe_sqlite3.so`
	- `./slskd`

_**edit:** updated for 15.0_

**Comment by tulse-luper** [comment]
aaaah so many thx @320x200 !!! this worked! was doing this in a jail on TrueNAS facilitating 13.4 release image.

a little detail for those who'll be doing this on TrueNAS (in a bsd jail): allow_mlock jail property should be enabled in order for the jail to execute dotnet binary. there's multiple explanations on this detail with dotnet and mlock for those who interested, but not a subject to our topic.

@320x200 what a magician you are! was hoping to find some recipe for this for a year!!!

someone clever, please merge this into pkg, make a target in Makefile or whatever=)

**Comment by panzertime** [comment]
Here's my rc script:

```
#!/bin/sh

# PROVIDE: slskd
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable slskd:
# slskd_enable : set to "YES" to enable the daemon, default is "NO"

. /etc/rc.subr

name=slskd
rcvar=slskd_enable

load_rc_config $name

slskd_enable=${slskd_enable:-"NO"}

logfile="/var/log/${name}.log"
slskd_chdir="/root"

procname="/home/sue/slskd"
command="/usr/sbin/daemon"
command_args="-u sue -o ${logfile} -t ${name} -r /home/sue/slskd"

run_rc_command "$1"
```

(assuming that you're running slsk as a user named `sue` and that your `slskd` binary is in that home directory)

I ran into that same hostname resolution issue. I'm trying to remember what the cause and solution were - I vaguely remember deciding it was a `dotnet` bug.

**Comment by panzertime** [comment]
Okay, having gone back through my notes, I do believe it is due to the use of `Dns.GetHostEntry` in the Soulseek.NET [library](https://github.com/jpdillingham/Soulseek.NET/blob/3ee7e3bbe4bd70e367d49aef95485aa682f32f7d/src/SoulseekClient.cs#L826), which fails when your host can't retrieve PTR records for a lookup, [apparently](https://stackoverflow.com/questions/4896180/dns-gethostentry-error-conditions-and-resolution-methods). 

This comes into play when `ConnectAsync` is called [here](https://github.com/slskd/slskd/blob/bac18981efba4daa4e4668dd382b7fbed8765636/src/slskd/Core/API/Controllers/ServerController.cs#L73)

**Comment by tschettervictor** [comment]
Interesting. I tried adding that to my hosts file as well, but still couldn’t run it.

I’m not running the program from the users home directory. I’m just running it out of /usr/local/www/slskd but with slskd as the user.

Would that affect anything?

**Comment by panzertime** [comment]
The rc script won't run your program unless you modify it to match your configuration, which is an exercise left to the reader.

**Comment by tschettervictor** [comment]
> The rc script won't run your program unless you modify it to match your configuration, which is an exercise left to the reader.

My rc script works fine. It loads everything, the WeUI etc…

The only thing that strand with is resolving the hostname.

**Comment by tschettervictor** [comment]
I think I've got it. The problem was the `chdir` needs to be set to the below, then it works.

`${name}_chdir=/root`

**Comment by tschettervictor** [comment]
Greetings again. Now we are running into this issue. It is failing to build on FreeBSD 14.x with the following error.

```
    /slskd/src/slskd/slskd.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org

Restore failed with 1 error(s) in 8.2s
    /slskd/src/slskd/slskd.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.freebsd-x64. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org
    /slskd/src/slskd/slskd.csproj : error NU1101: Unable to find package Microsoft.AspNetCore.App.Runtime.freebsd-x64. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org
    /slskd/src/slskd/slskd.csproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.freebsd-x64. No packages exist with this id in source(s): /usr/local/share/dotnet/library-packs, nuget.org

Restore failed with 3 error(s) in 7.4s
```


Checking https://www.nuget.org/packages?q=freebsd shows that the packages for FreeBSD are deprecated. Also, I cannot find those exact package names there at all.

The packages do seem to exist inside `/usr/local/share/dotnet/library-packs` so I'm not sure what is going on really.

Has anyone been able to build this lately under FreeBSD 14?

**Comment by jonasoh** [comment]
So, this is what I do to compile slskd on FreeBSD 14.2, currently (with `lang/dotnet` 9.0.3):

```
cd src/slskd
sed -i '' s/net8.0/net9.0/ slskd.csproj  # set the target framework to net9.0
dotnet publish \
  -c Release \
  --runtime freebsd.14-x64 \
  --framework net9.0 \
  -p:ReadyToRun=true \
  -p:PublishSingleFile=true \
  -p:IncludeNativeLibrariesForSelfExtract=true \
  -p:Version=$(git describe --tags --abbrev=0)+$(git rev-parse --short HEAD) \
  --output ../../dist/freebsd.14-x64 \
  --self-contained &&
ln -sf /usr/local/lib/libsqlite3.so ../../dist/freebsd.14-x64/libe_sqlite3.so
```

I don't know what difference the `--framework` and `--runtime` options do, if any. the `-p:CopyOutputSymbolsToPublishDirectory=false`, which is used in the  `bin/publish` script, makes the build fail so it's been omitted here.

**Comment by tschettervictor** [comment]
Hmmm. Just tried this and it's still not working for me.
I get the below error.

`Failed to create CoreCLR, HRESULT: 0x8007FF02
Failed to create CoreCLR, HRESULT: 0x8007FF02`

**Comment by jonasoh** [comment]
I just installed slskd 0.25.1 on FreeBSD 15.0 and had to slightly modify my build command from above. FreeBSD 15 has a new runtime name, and the current slskd targets .NET 10.0 (`lang/dotnet` is still on 9.0). So, to build on FreeBSd 15.0, I would run:

```
cd src/slskd
sed -i '' s/net10.0/net9.0/ slskd.csproj
dotnet publish \
  -c Release \
  --runtime freebsd.15-x64 \
  --framework net9.0 \
  -p:ReadyToRun=true \
  -p:PublishSingleFile=true \
  -p:IncludeNativeLibrariesForSelfExtract=true \
  -p:Version=$(git describe --tags --abbrev=0)+$(git rev-parse --short HEAD) \
  --output ../../dist/freebsd.15-x64 \
  --self-contained &&
ln -sf /usr/local/lib/libsqlite3.so ../../dist/freebsd.15-x64/libe_sqlite3.so
```

**Comment by jpdillingham** [comment]
I had to upgrade to .NET 10 so that the `listen_ip_address` setting is respected (#1693); keep this in mind if you're using that setting.

If folks have found a repeatable process that works well, we can update the build to produce binaries.  I haven't used it but the [freebsd-vm](https://github.com/marketplace/actions/freebsd-vm) action can boot a freebsd VM.  I'd be a bit concerned about how much time it would take so canary builds are probably out of the question but it should be ok for releases.

**Comment by tschettervictor** [comment]
> I had to upgrade to .NET 10 so that the `listen_ip_address` setting is respected (#1693); keep this in mind if you're using that setting.
> 
> If folks have found a repeatable process that works well, we can update the build to produce binaries.  I haven't used it but the [freebsd-vm](https://github.com/marketplace/actions/freebsd-vm) action can boot a freebsd VM.  I'd be a bit concerned about how much time it would take so canary builds are probably out of the question but it should be ok for releases.

I will run my install script again in the next few days to see if it still builds properly.

https://github.com/tschettervictor/bsd-apps

EDIT: I'm getting stuck at the `dotnet build...` command. It's returning `Failed to create CoreCLR, HRESULT: 0x8007FF02`

FreeBSD 14.4

EDIT2: forgot to set allow.mlock

Working great.

**Comment by jonasoh** [comment]
I think it would be very nice to have a FreeBSD CI build and would offer my help in maintaining it. It would probably need to be clearly marked as experimental for a while. I see a couple problems (aside from my complete lack of .NET knowledge). 

– There is currently no official .NET 10 in the ports tree. There are builds maintained by individuals, such as https://github.com/sec/dotnet-core-freebsd-source-build. I'm not sure about the pitfalls of using this for packaging, other than perhaps trust issues. I just built HEAD on FreeBSD 15.0 using that on a fresh VM and it seems to be working. There is also a `lang/dotnet-devel` port, but this is not in packages and thus might cause long runtimes on a CI setup. Might be wise to wait for an update of the dotnet package, but I also guess that this isn't the last time FreeBSD will be behind in this area...

– For properly building/running, I needed to symlink certain system libs, like libcrypto.so, into the places where dotnet wants them to be. This is more complicated than the libe_sqlite3 issue, since it doesn't look in the dist dir for these libs. The cleanest way I can come up with is to have a run/build script which sets LD_LIBRARY_PATH and then symlinks system libs into that dir. Not very polished, but might work well enough. Someone with more .NET knowledge might know a better way to accomplish this.

**Comment by jonasoh** [comment]
I tested the `listen_ip_address` functionality on a FreeBSD build on net9.0 just now, and it works as expected. If targeting .NET 9.0 is fine, then slskd would build on FreeBSD with only minimal changes:
– Change shebang lines in build scripts from `#!/bin/bash` to `#!/bin/sh`.
– Linking `/usr/local/lib/libsqlite3.so` to `../../dist/freebsd.14-x64/libe_sqlite3.so` after successful build.

**Comment by shmoinkle** [comment]
Been manually building slskd for a while on my derpy XigmaNAS jail, thanks to the information everyone has posted in this issue.

I'm happy to say, I've had success in getting slskd to build in a poudriere environment. As such, I've submitted the patch to get slskd added into the ports tree:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=295545

And I'll also maintain the port here:
https://github.com/shmoinkle/slskd-port

Hopefully this means pkg installing slskd in the future. I'll be sure to update here when/if

None of this would have been possible without everyone's contribution in this issue.

Thanks, y'all. Long live Soulseek~

**Comment by tschettervictor** [comment]
Any build anymore with dotnet9?

Errors are saying "Asp.Versioning.Mvc.ApiExplorer 10.0.0 is not compatible with dotnet9"

**Comment by jonasoh** [comment]
I managed to build HEAD using the 10.0.110 build from https://github.com/sec/dotnet-core-freebsd-source-build. Just did a quick test, but it seems to function as it should. There is probably a "correct" way to install this build, but to build it quickly i basically:

```
# extract the contents of dotnet-sdk-10.0.110-freebsd.15-x64.tar.gz to e.g. ~/dotnet10
export PATH=~/dotnet10:$PATH
cd src/slskd/src/slskd
dotnet publish \
  -c Release \
  --runtime freebsd.15-x64 \
  -p:ReadyToRun=true \
  -p:PublishSingleFile=true \
  -p:IncludeNativeLibrariesForSelfExtract=true \
  -p:Version=$(git describe --tags --abbrev=0)+$(git rev-parse --short HEAD) \
  --output ../../dist/freebsd.15-x64 \
  --self-contained
ln -sf /usr/local/lib/libsqlite3.so ../../dist/freebsd.15-x64/libe_sqlite3.so
```

 @shmoinkle Any updates on getting the port into the ports tree? Is it possible to get around the net9.0 build error using your nuget trick?
